### ISSUE TITLE
[BUG] segfault in capstone disasm

### ISSUE THREAD

**Issue by sh4m2hwz** [falconre/falcon#122]
``` 
Program received signal SIGSEGV, Segmentation fault.
0x000055555589f221 in falcon_capstone::capstone::Instr::new () at src/capstone.rs:192
192	            let detail = unsafe { *instr.detail };
(gdb) bt
#0  0x000055555589f221 in falcon_capstone::capstone::Instr::new ()
    at src/capstone.rs:192
#1  falcon_capstone::capstone::InstrBuf::get () at src/capstone.rs:395
#2  0x0000555555858ea7 in falcon::translator::x86::translator::translate_block
    () at lib/translator/x86/translator.rs:90
#3  0x0000555555831f7f in falcon::translator::x86::{impl#3}::translate_block ()
    at lib/translator/x86/mod.rs:54
#4  falcon::translator::Translator::translate_function_extended<falcon::translator::x86::Amd64> () at lib/translator/mod.rs:163
#5  0x0000555555784c49 in falcon::loader::Loader::program_verbose<falcon::loader::elf::elf_linker::ElfLinker> ()
    at /home/godtex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/falcon-0.5.5/lib/loader/mod.rs:150
#6  falcon::loader::Loader::program_recursive_verbose<falcon::loader::elf::elf_linker::ElfLinker> ()
    at /home/godtex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/falcon-0.5.5/lib/loader/mod.rs:198
#7  falcon::loader::Loader::program_recursive<falcon::loader::elf::elf_linker::ElfLinker> ()
    at /home/godtex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/falcon-0.5.5/lib/loader/mod.rs:169
```

**Comment by sh4m2hwz** [comment]
[dependencies]
falcon = {version = "0.5.5", features = []}
falcon-z3 = { version = "0.5.2", features = [] }
